export const courses = [
  {
    id: 1,
    title: "React - The Complete Guide",
    instructor: "John Smith",
    price: 49.99,
    rating: 4.7,
    students: "32K",
    image:
      "https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=1200&auto=format&fit=crop",
    description:
      "Learn React from scratch and build powerful web applications with confidence.",
    role: "Senior Frontend Engineer",
    lessons: [
      "1.Introduction",
      "2.React Basics",
      "3.Components",
      "4.State and Props",
      "5.Hooks",
    ],
  },
  {
    id: 2,
    title: "JavaScript Mastery",
    instructor: "Emily Johnson",
    price: 39.99,
    rating: 4.6,
    role: "JavaScript Developer",
    students: "27K",
    image: "/js.png",
    description: "Master JavaScript fundamentals and advanced topics.",
    lessons: ["1.Variables", "2.Functions", "3.DOM", "4.ES6"],
  },
  {
    id: 3,
    title: "UI/UX Design Fundamentals",
    instructor: "David Lee",
    price: 44.99,
    rating: 4.4,
    role: "UI/UX Designer",
    students: "18K",
    image: "/ui.png",
    description: "Design modern and user-friendly interfaces.",
    lessons: ["1.Colors", "2.Typography", "3.Wireframes"],
  },
  {
    id: 4,
    title: "Node.js & Express",
    instructor: "Sarah Wilson",
    price: 54.99,
    rating: 4.6,
    students: "21K",
    role: "Backend Engineer",
    image: "/node.png",
    description: "Build backend applications using Node.js.",
    lessons: ["1.Setup", "2.APIs", "3.Routing"],
  },
  {
    id: 5,
    title: "Python for Beginners",
    instructor: "Michael Brown",
    price: 34.99,
    rating: 4.5,
    students: "29K",
    image: "/python.jpg",
    role: "Python Developer",
    description: "Start programming with Python easily.",
    lessons: ["1.Basics", "2.Loops", "3.Functions"],
  },
  {
    id: 6,
    title: "Figma UI Design",
    instructor: "Jessica Davis",
    price: 29.99,
    role: "Product Designer",
    rating: 4.7,
    students: "15K",
    image: "/figma.jpg",
    description: "Design professional UI using Figma.",
    lessons: ["1.Layouts", "2.Components"],
  },
  {
    id: 7,
    title: "Next.js Crash Course",
    instructor: "Daniel Martinez",
    price: 59.99,
    role: "Fullstack Developer",
    rating: 4.8,
    students: "12K",
    image: "/next.png",
    description: "Build fullstack apps with Next.js.",
    lessons: ["1.Routing", "2.SSR"],
  },
  {
    id: 8,
    title: "SQL for Data Analysis",
    instructor: "James Wilson",
    price: 39.99,
    role: "Data Analyst",

    rating: 4.5,
    students: "10K",
    image: "/data.jpg",
    description: "Analyze data using SQL.",
    lessons: ["1.Queries", "2.Joins"],
  },
  {
    id: 9,
    title: "Photoshop Masterclass",
    instructor: "Olivia Taylor",
    price: 49.99,
    role: "Graphic Designer",
    rating: 4.6,
    students: "17K",
    image: "/ps.jpg",
    description: "Master Photoshop for design.",
    lessons: ["1.Tools", "2.Editing"],
  },
];

export const heroCourses = [
  {
    id: 1,
    title: "React - The Complete Guide",
    instructor: "John Smith",
    price: 49.99,
    rating: 4.7,
    students: "32K",
    image: "/react.jpg",
  },
  {
    id: 2,
    title: "JavaScript Mastery",
    instructor: "Emily Johnson",
    price: 39.99,
    rating: 4.6,
    students: "27K",
    image: "/js.png",
  },
  {
    id: 3,
    title: "UI/UX Design Fundamentals",
    instructor: "David Lee",
    price: 44.99,
    rating: 4.4,
    students: "18K",
    image: "/ui.png",
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Sarah Johnson",
    role: "UI Designer",
    image: "/user1.png",
    review: "This platform helped me improve my skills and land my dream job!",
  },

  {
    id: 2,
    name: "Michael Brown",
    role: "Frontend Developer",
    image: "/user2.png",
    review: "Best learning platform ever. Easy to follow and practical.",
  },

  {
    id: 3,
    name: "Emily Davis",
    role: "Product Manager",
    image: "/user3.png",
    review: "Highly recommend for anyone looking to grow fast.",
  },
];
export const footerData = [
  {
    id: 1,
    title: "Platform",
    links: ["Courses", "Categories", "Instructors", "Pricing"],
  },

  {
    id: 2,
    title: "Company",
    links: ["About Us", "Blog", "Careers", "Contact"],
  },

  {
    id: 3,
    title: "Support",
    links: [
      "Help Center",
      "Terms of Service",
      "Privacy Policy",
      "Refund Policy",
    ],
  },
];
