export const courses = [
  {
    id: 1,
    title: "React - The Complete Guide",
    instructor: "John Smith",
    price: 49.99,
    rating: 4.7,
    students: "32K",
    image: "/react.jpg",
    description:
      "Learn React from scratch and build powerful web applications.",
    lessons: [
      "Introduction",
      "React Basics",
      "Components",
      "State and Props",
      "Hooks",
    ],
  },
  {
    id: 2,
    title: "JavaScript Mastery",
    instructor: "Emily Johnson",
    price: 39.99,
    rating: 4.6,
    students: "27K",
    image: "/js.png",
    description: "Master JavaScript fundamentals and advanced topics.",
    lessons: ["Variables", "Functions", "DOM", "ES6"],
  },
  {
    id: 3,
    title: "UI/UX Design Fundamentals",
    instructor: "David Lee",
    price: 44.99,
    rating: 4.4,
    students: "18K",
    image: "/ui.png",
    description: "Design modern and user-friendly interfaces.",
    lessons: ["Colors", "Typography", "Wireframes"],
  },
  {
    id: 4,
    title: "Node.js & Express",
    instructor: "Sarah Wilson",
    price: 54.99,
    rating: 4.6,
    students: "21K",
    image: "/node.png",
    description: "Build backend applications using Node.js.",
    lessons: ["Setup", "APIs", "Routing"],
  },
  {
    id: 5,
    title: "Python for Beginners",
    instructor: "Michael Brown",
    price: 34.99,
    rating: 4.5,
    students: "29K",
    image: "/python.jpg",
    description: "Start programming with Python easily.",
    lessons: ["Basics", "Loops", "Functions"],
  },
  {
    id: 6,
    title: "Figma UI Design",
    instructor: "Jessica Davis",
    price: 29.99,
    rating: 4.7,
    students: "15K",
    image: "/figma.jpg",
    description: "Design professional UI using Figma.",
    lessons: ["Layouts", "Components"],
  },
  {
    id: 7,
    title: "Next.js Crash Course",
    instructor: "Daniel Martinez",
    price: 59.99,
    rating: 4.8,
    students: "12K",
    image: "/next.png",
    description: "Build fullstack apps with Next.js.",
    lessons: ["Routing", "SSR"],
  },
  {
    id: 8,
    title: "SQL for Data Analysis",
    instructor: "James Wilson",
    price: 39.99,
    rating: 4.5,
    students: "10K",
    image: "/data.jpg",
    description: "Analyze data using SQL.",
    lessons: ["Queries", "Joins"],
  },
  {
    id: 9,
    title: "Photoshop Masterclass",
    instructor: "Olivia Taylor",
    price: 49.99,
    rating: 4.6,
    students: "17K",
    image: "/ps.jpg",
    description: "Master Photoshop for design.",
    lessons: ["Tools", "Editing"],
  },
];

export const heroCourses = [
  {
    id: 1,
    title: "React - The Complete Guide",
    instructor: "John Smith",
    price: 49.99,
    rating: 4.7,
    students: "32K",
    image: "/react.jpg",
  },
  {
    id: 2,
    title: "JavaScript Mastery",
    instructor: "Emily Johnson",
    price: 39.99,
    rating: 4.6,
    students: "27K",
    image: "/js.png",
  },
  {
    id: 3,
    title: "UI/UX Design Fundamentals",
    instructor: "David Lee",
    price: 44.99,
    rating: 4.4,
    students: "18K",
    image: "/ui.png",
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Sarah Johnson",
    role: "UI Designer",
    image: "/user1.png",
    review: "This platform helped me improve my skills and land my dream job!",
  },

  {
    id: 2,
    name: "Michael Brown",
    role: "Frontend Developer",
    image: "/user2.png",
    review: "Best learning platform ever. Easy to follow and practical.",
  },

  {
    id: 3,
    name: "Emily Davis",
    role: "Product Manager",
    image: "/user3.png",
    review: "Highly recommend for anyone looking to grow fast.",
  },
];
export const footerData = [
  {id:1,
    title: "Platform" ,
    links: ["Courses", "Categories", "Instructors", "Pricing"]},

  {id:2,
    title:'Company',
  links: ["About Us", "Blog", "Careers", "Contact"]},

  {id:3,
    title:'Support',
  links: [
    "Help Center",
    "Terms of Service",
    "Privacy Policy",
    "Refund Policy",
  ]},
];
